version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp_todo_list
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      todo-list-app:

  back:
    build: 
      context: ./todo_list_back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "8090:8090"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tp_todo_list
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      todo-list-app:
  front:
    build: 
      context: ./todo_list_front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - '80:80'
    depends_on:
      - back
    networks:
      todo-list-app:



networks:
  todo-list-app:
volumes:
  mysql-data:
