services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp_todo_list
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    image: todo_list_back-application:latest
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tp_todo_list
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql-data:
